update = Update
change_language = Languages
homepage = Homepage
open_folder = Open Folder
waiting_sc_process = Waiting StarCraft: Remastered Process...
waiting_sc_module = Waiting StarCraft: Remastred Module...
fail_to_read_memory = Fail to read memory...
waiting_map_using_umsbank = Waiting UMS map using umsbank...